// Builds supabase/seed.sql from src/data/content.json (the single source of starter content).
import fs from 'node:fs'
const c=JSON.parse(fs.readFileSync('src/data/content.json','utf8'))
const q=v=>v==null?'null':typeof v==='number'?String(v):`'${String(v).replace(/'/g,"''")}'`
const j=v=>`${q(JSON.stringify(v))}::jsonb`
const out=['-- Generated by `npm run seed` from src/data/content.json. Safe to re-run.']
// Upsert on the conflict key so re-running after an edit (e.g. a changed video_url)
// actually updates existing rows instead of silently no-op'ing against them.
const ins=(t,cols,rows,conflictKey)=>{
 if(!rows.length)return
 const colList=cols.split(', ')
 const updateCols=colList.filter(col=>col!==conflictKey)
 const conflictClause=updateCols.length
  ?`on conflict (${conflictKey}) do update set ${updateCols.map(col=>`${col} = excluded.${col}`).join(', ')}`
  :`on conflict (${conflictKey}) do nothing`
 out.push(`insert into public.${t} (${cols}) values\n${rows.map(r=>`  (${r.join(', ')})`).join(',\n')}\n${conflictClause};`)
}
ins('lessons','slug, title, summary, video_url, minutes, position',c.lessons.map((l,i)=>[q(l.slug),q(l.title),q(l.summary),q(l.video_url),l.minutes,i+1]),'slug')
ins('steps','id, lesson_slug, position, title, body',c.lessons.flatMap(l=>l.steps.map((s,i)=>[q(s.id),q(l.slug),i+1,q(s.title),q(s.body)])),'id')
ins('quiz_questions','id, step_id, question, options, answer, explanation',c.lessons.flatMap(l=>l.steps.flatMap(s=>s.quiz_questions.map(z=>[q(z.id),q(s.id),q(z.question),j(z.options),z.answer,q(z.explanation)]))),'id')
ins('checklists','slug, title, items, position',c.checklists.map((k,i)=>[q(k.slug),q(k.title),j(k.items),i+1]),'slug')
ins('parts','slug, name, fn, x, y, position',c.parts.map((p,i)=>[q(p.slug),q(p.name),q(p.fn),p.x,p.y,i+1]),'slug')
ins('faqs','q, a, position',c.faqs.map((f,i)=>[q(f.q),q(f.a),i+1]),'q')
ins('achievements','slug, title, description, criteria, position',c.achievements.map((a,i)=>[q(a.slug),q(a.title),q(a.description),q(a.criteria),i+1]),'slug')
fs.mkdirSync('supabase',{recursive:true});fs.writeFileSync('supabase/seed.sql',out.join('\n\n')+'\n')
